# Generated by Django 4.0.2 on 2022-02-21 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0002_rename_tags_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_id', models.IntegerField()),
                ('seat_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=60)),
                ('alignment', models.CharField(max_length=60)),
                ('backstory', models.CharField(max_length=300)),
                ('hero_class', models.CharField(max_length=60)),
                ('race', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('wisdom', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='hero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_import.hero'),
        ),
    ]
