# Generated by Django 4.0.2 on 2022-02-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0003_hero_alter_tag_id_tag_hero'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('hero', 'label')},
        ),
        migrations.AddConstraint(
            model_name='hero',
            constraint=models.UniqueConstraint(fields=('game_id',), name='game_id'),
        ),
    ]
