# Generated by Django 4.0.2 on 2022-02-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0004_alter_tag_unique_together_hero_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='alignment',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='backstory',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='charisma',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='constitution',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='dexterity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='full_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='hero_class',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='intelligence',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='race',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='seat_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='strength',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='wisdom',
            field=models.IntegerField(null=True),
        ),
    ]
