# Generated by Django 4.0.2 on 2022-02-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0005_alter_hero_age_alter_hero_alignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
