# Generated by Django 4.0.2 on 2022-02-21 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0006_alter_hero_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='hero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='data_import.hero'),
        ),
    ]
