# Generated by Django 4.0.2 on 2022-02-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0007_alter_tag_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='availability',
            field=models.CharField(choices=[('CORE', 'Core'), ('EVERGREEN', 'EverGreen'), ('TIMEGATE', 'TimeGate'), ('EVENT', 'Event')], default='EVENT', max_length=12),
        ),
    ]
