# Generated by Django 4.0.2 on 2022-02-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0008_hero_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='should_pay_tribute',
            field=models.BooleanField(default=False),
        ),
    ]
