# Generated by Django 4.0.2 on 2022-02-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0009_hero_should_pay_tribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hero',
            name='should_pay_tribute',
            field=models.BooleanField(default=False, verbose_name='GOAT'),
        ),
    ]
