# Generated by Django 4.0.2 on 2022-02-23 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0010_hero_is_unlocked_alter_hero_should_pay_tribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_id', models.IntegerField(null=True)),
                ('enchant', models.IntegerField(null=True)),
                ('rarity', models.IntegerField(default=1)),
                ('gild', models.IntegerField(default=0)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_import.hero')),
            ],
            options={
                'unique_together': {('hero', 'slot_id')},
            },
        ),
    ]
