# Generated by Django 4.0.2 on 2022-02-24 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0011_loot'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='average_loot_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loot',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loots', to='data_import.hero'),
        ),
    ]
